name: flynott
description: Encrypted notes with style.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  go_router: ^9.0.0
  google_fonts: ^5.1.0
  flutter_staggered_grid_view: ^0.6.2
  flutter_quill: ^7.2.11
  intl: ^0.18.1
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true